/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/parameters`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/menu/controlPanel`; params?: Router.UnknownInputParams; } | { pathname: `/menu/report`; params?: Router.UnknownInputParams; } | { pathname: `/menu/validacion`; params?: Router.UnknownInputParams; } | { pathname: `/menu/tabs/DetallePallet`; params?: Router.UnknownInputParams; } | { pathname: `/menu/tabs/RechazoPallet`; params?: Router.UnknownInputParams; } | { pathname: `/menu/tabs/RechazoPallet_new`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/menu`; params?: Router.UnknownOutputParams; } | { pathname: `/parameters`; params?: Router.UnknownOutputParams; } | { pathname: `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/controlPanel`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/report`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/validacion`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/tabs/DetallePallet`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/tabs/RechazoPallet`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/tabs/RechazoPallet_new`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/menu${`?${string}` | `#${string}` | ''}` | `/parameters${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/menu/controlPanel${`?${string}` | `#${string}` | ''}` | `/menu/report${`?${string}` | `#${string}` | ''}` | `/menu/validacion${`?${string}` | `#${string}` | ''}` | `/menu/tabs/DetallePallet${`?${string}` | `#${string}` | ''}` | `/menu/tabs/RechazoPallet${`?${string}` | `#${string}` | ''}` | `/menu/tabs/RechazoPallet_new${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/menu`; params?: Router.UnknownInputParams; } | { pathname: `/parameters`; params?: Router.UnknownInputParams; } | { pathname: `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/menu/controlPanel`; params?: Router.UnknownInputParams; } | { pathname: `/menu/report`; params?: Router.UnknownInputParams; } | { pathname: `/menu/validacion`; params?: Router.UnknownInputParams; } | { pathname: `/menu/tabs/DetallePallet`; params?: Router.UnknownInputParams; } | { pathname: `/menu/tabs/RechazoPallet`; params?: Router.UnknownInputParams; } | { pathname: `/menu/tabs/RechazoPallet_new`; params?: Router.UnknownInputParams; };
    }
  }
}
